name: doctoworld_doctor
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+3

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_phoenix: ^1.0.0
  flutter_bloc: ^7.0.0
  percent_indicator: ^3.0.1
  animation_wrappers: ^0.0.4
  dio:
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  google_fonts:
  flutter_svg: ^0.22.0
  geolocator:
  geocoding:
  image_picker: ^0.8.4
  datetime_picker_formfield: ^1.0.0
  flutter_slidable: ^0.6.0
  expansion_tile_card: ^2.0.0
  flutter_local_notifications:
  agora_rtc_engine:
  get:
  get_storage:
  permission_handler:
  pusher_client:
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.1
  firebase_messaging:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/doctors/

  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf